File "/opt/render/project/src/personal_account_autoreply.py", line 10, in <module>
    from pyrogram import Client, filters
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pyrogram/init.py", line 40, in <module>
    from .sync import idle, compose
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pyrogram/sync.py", line 99, in <module>
    wrap(Methods)
    ~~~~^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pyrogram/sync.py", line 95, in wrap
    async_to_sync(source, name)
    ~~~~~^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pyrogram/sync.py", line 31, in async_to_sync
    main_loop = asyncio.get_event_loop()
  File "/opt/render/project/python/Python-3.13.4/lib/python3.13/asyncio/events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'PersonalBotThread'.
==> Your service is live ðŸŽ‰
==> 
==> ///////////////////////////////////////////////////////////
==> 
==> Available at your primary URL https://telegram-ai-bot-chatbot.onrender.com
==> 
==> ///////////////////////////////////////////////////////////
2025-10-19 23:20:15,597 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8267153211:AAHc0HDFylsWNx7uqC2_hb2HLnC-y0VB_1w/getUpdates "HTTP/1.1 409 Conflict"
2025-10-19 23:20:15,598 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:15,598 - main - ERROR - Update None caused error Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:21,482 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8267153211:AAHc0HDFylsWNx7uqC2_hb2HLnC-y0VB_1w/getUpdates "HTTP/1.1 409 Conflict"
2025-10-19 23:20:21,482 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:21,483 - main - ERROR - Update None caused error Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:28,615 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8267153211:AAHc0HDFylsWNx7uqC2_hb2HLnC-y0VB_1w/getUpdates "HTTP/1.1 409 Conflict"
2025-10-19 23:20:28,615 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:28,615 - main - ERROR - Update None caused error Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:34,671 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8267153211:AAHc0HDFylsWNx7uqC2_hb2HLnC-y0VB_1w/getUpdates "HTTP/1.1 409 Conflict"
2025-10-19 23:20:34,672 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:34,672 - main - ERROR - Update None caused error Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:43,965 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8267153211:AAHc0HDFylsWNx7uqC2_hb2HLnC-y0VB_1w/getUpdates "HTTP/1.1 409 Conflict"
2025-10-19 23:20:43,966 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-10-19 23:20:43,966 - main - ERROR - Update None caused error Conflict: